
-- Clear existing verses to avoid conflicts
DELETE FROM daily_verses;

-- Insert all 366 verses
INSERT INTO daily_verses (day_of_year, verse_text, verse_reference) VALUES
(1, 'Deus faz novas todas as coisas; um novo começo está diante de você.', 'Apocalipse 21:5'),
(2, 'Confie no Senhor de todo o coração e não dependa apenas do seu próprio entendimento.', 'Provérbios 3:5'),
(3, 'Feliz quem age com bondade para com o fraco; o Senhor o sustenta no dia da dificuldade.', 'Salmos 41:1'),
(4, 'Se faltar sabedoria, peça a Deus, e ele dará com generosidade.', 'Tiago 1:5'),
(5, 'Tudo o que você fizer, faça de todo o coração, como para o Senhor.', 'Colossenses 3:23'),
(6, 'Seja forte e corajoso; não tenha medo, porque o Senhor está com você.', 'Josué 1:9'),
(7, 'Façam aos outros exatamente o que vocês desejam que façam a vocês.', 'Lucas 6:31'),
(8, 'Entreguem a Deus suas preocupações, e a paz dele guardará coração e mente.', 'Filipenses 4:6-7'),
(9, 'Há um tempo certo para cada propósito debaixo do céu.', 'Eclesiastes 3:1'),
(10, 'O prudente percebe o perigo e age com cautela.', 'Provérbios 22:3'),
(11, 'Revistam-se de compaixão, bondade, humildade, mansidão e paciência.', 'Colossenses 3:12'),
(12, 'Ensina-nos a contar os nossos dias para que alcancemos coração sábio.', 'Salmos 90:12'),
(13, 'O Senhor fortalece o cansado e dá vigor ao que está sem forças.', 'Isaías 40:29'),
(14, 'O amor deve ser sincero; apeguem-se ao bem.', 'Romanos 12:9'),
(15, 'Melhor é adquirir sabedoria do que ouro; entendimento vale mais que prata.', 'Provérbios 16:16'),
(16, 'Venham a mim, vocês que estão cansados e sobrecarregados, e eu lhes darei descanso.', 'Mateus 11:28'),
(17, 'A resposta calma desvia a tensão, mas a palavra dura aumenta o conflito.', 'Provérbios 15:1'),
(18, 'Levem os fardos uns dos outros e assim cumprirão a lei de Cristo.', 'Gálatas 6:2'),
(19, 'Lance sobre Deus toda a sua ansiedade, porque ele cuida de você.', '1 Pedro 5:7'),
(20, 'A boca do sábio espalha conhecimento no tempo certo.', 'Provérbios 15:7'),
(21, 'O Senhor é meu pastor; tenho tudo de que realmente preciso.', 'Salmos 23:1'),
(22, 'Não se cansem de fazer o bem, pois no tempo certo haverá colheita.', 'Gálatas 6:9'),
(23, 'Onde não há boa direção, os planos fracassam; com conselhos sábios, eles se firmam.', 'Provérbios 15:22'),
(24, 'Sejam bondosos e compassivos uns com os outros.', 'Efésios 4:32'),
(25, 'O coração alegre favorece a vida e renova as forças.', 'Provérbios 17:22'),
(26, 'Jesus viu a multidão e teve compaixão dela, porque estava aflita e sem direção.', 'Mateus 9:36'),
(27, 'Acima de tudo, guarde o coração, porque dele procedem as fontes da vida.', 'Provérbios 4:23'),
(28, 'Deus é o nosso refúgio e fortaleza, auxílio sempre presente nas dificuldades.', 'Salmos 46:1'),
(29, 'Quem é fiel no pouco também é fiel no muito.', 'Lucas 16:10'),
(30, 'Que a paz de Cristo governe o coração de vocês.', 'Colossenses 3:15'),
(31, 'Entregue ao Senhor o seu trabalho, e seus planos serão estabelecidos.', 'Provérbios 16:3'),
(32, 'A sabedoria do alto é pura, pacífica, amável, tratável e cheia de bons frutos.', 'Tiago 3:17'),
(33, 'O Senhor vai à sua frente; ele estará com você e não o abandonará.', 'Deuteronômio 31:8'),
(34, 'Sirvam uns aos outros com amor.', 'Gálatas 5:13'),
(35, 'O sábio escuta e aumenta seu entendimento.', 'Provérbios 1:5'),
(36, 'Senhor, firma o trabalho das nossas mãos.', 'Salmos 90:17'),
(37, 'Deus não nos deu espírito de medo, mas de poder, amor e equilíbrio.', '2 Timóteo 1:7'),
(38, 'Alegrem-se na esperança, sejam pacientes na tribulação e perseverem na oração.', 'Romanos 12:12'),
(39, 'Quem refresca os outros também será renovado.', 'Provérbios 11:25'),
(40, 'Jesus percorria cidades e povoados, ensinando, anunciando e curando.', 'Mateus 9:35'),
(41, 'É melhor ter sabedoria do que força; o conhecimento vale mais que o vigor.', 'Eclesiastes 9:16'),
(42, 'Eu o instruirei e o ensinarei no caminho que você deve seguir.', 'Salmos 32:8'),
(43, 'Seja humilde no trato com todos e considere o outro com atenção sincera.', 'Filipenses 2:3-4'),
(44, 'A pessoa bondosa faz bem a si mesma.', 'Provérbios 11:17'),
(45, 'Meu Deus suprirá tudo o que vocês precisam.', 'Filipenses 4:19'),
(46, 'Aquele que começou a boa obra em vocês a completará.', 'Filipenses 1:6'),
(47, 'Melhor dois do que um, porque juntos têm melhor resultado no trabalho.', 'Eclesiastes 4:9'),
(48, 'Tenham cuidado com a maneira como vivem; vivam com sabedoria.', 'Efésios 5:15'),
(49, 'O Senhor sustenta todos os que estão caindo e levanta os abatidos.', 'Salmos 145:14'),
(50, 'Permaneçam firmes e constantes, sempre dedicados à obra do Senhor.', '1 Coríntios 15:58'),
(51, 'Amem uns aos outros da mesma forma que Cristo amou vocês.', 'João 15:12'),
(52, 'As palavras impulsivas ferem, mas a fala sábia pode trazer alívio e restauração.', 'Provérbios 12:18'),
(53, 'O Senhor guarda sua saída e sua chegada, hoje e sempre.', 'Salmos 121:7-8'),
(54, 'Melhor é o fim das coisas do que o começo; a perseverança vale mais que a pressa.', 'Eclesiastes 7:8'),
(55, 'Mantenha os olhos em Jesus e siga com constância na corrida que está diante de você.', 'Hebreus 12:2'),
(56, 'Quando você acolhe o aflito e socorre quem sofre, sua luz brilha em meio à escuridão.', 'Isaías 58:10'),
(57, 'Alegrem-se com os que se alegram e chorem com os que choram.', 'Romanos 12:15'),
(58, 'Quem responde antes de ouvir demonstra imprudência.', 'Provérbios 18:13'),
(59, 'Seja pronto para ouvir, cuidadoso ao falar e lento para se irritar.', 'Tiago 1:19'),
(60, 'Felizes os misericordiosos, porque receberão misericórdia.', 'Mateus 5:7'),
(61, 'Mesmo quando minhas forças falham, Deus continua sendo minha força e meu sustento.', 'Salmos 73:26'),
(62, 'Defenda quem não consegue se defender e faça justiça aos mais vulneráveis.', 'Provérbios 31:8-9'),
(63, 'Vá e pratique a mesma compaixão que você reconhece como correta.', 'Lucas 10:37'),
(64, 'Que sua fala seja sempre agradável, sábia e adequada a cada pessoa.', 'Colossenses 4:6'),
(65, 'Na calma e na confiança está a sua força.', 'Isaías 30:15'),
(66, 'A graça de Deus é suficiente para você, e o poder dele se aperfeiçoa na fraqueza.', '2 Coríntios 12:9'),
(67, 'A paciência revela entendimento; a pressa alimenta erros.', 'Provérbios 14:29'),
(68, 'Deus permanece com você e não o abandona.', 'Hebreus 13:5'),
(69, 'Quem confia no Senhor permanece firme e continua frutificando mesmo em tempos difíceis.', 'Jeremias 17:7-8'),
(70, 'O Senhor é quem cura, sustenta e orienta o caminho do seu povo.', 'Êxodo 15:26'),
(71, 'O Senhor firma os passos de quem anda com integridade e o sustenta quando tropeça.', 'Salmos 37:23-24'),
(72, 'Sirva com boa vontade, como quem trabalha diante de Deus.', 'Efésios 6:7'),
(73, 'Conheça bem aquilo que está sob sua responsabilidade e cuide com atenção do que foi confiado a você.', 'Provérbios 27:23'),
(74, 'Façam tudo sem murmurar nem reclamar, brilhando com integridade onde estiverem.', 'Filipenses 2:14-15'),
(75, 'Em Cristo há paz, mesmo em meio às pressões deste mundo.', 'João 16:33'),
(76, 'Planos se firmam com conselhos sábios e boa direção.', 'Provérbios 20:18'),
(77, 'Pratique a justiça, ame a misericórdia e ande com humildade diante de Deus.', 'Miqueias 6:8'),
(78, 'O Senhor está perto dos que têm o coração ferido.', 'Salmos 34:18'),
(79, 'Encorajem uns aos outros e ajudem-se mutuamente a permanecer firmes.', '1 Tessalonicenses 5:11'),
(80, 'A verdadeira sabedoria vem do Senhor; dele procedem entendimento e discernimento.', 'Provérbios 2:6'),
(81, 'Que sua vida produza amor, paz, bondade, mansidão e domínio próprio.', 'Gálatas 5:22-23'),
(82, 'Mantenho o Senhor diante de mim; com ele ao meu lado, não serei abalado.', 'Salmos 16:8'),
(83, 'Ouça conselhos e aceite instrução para agir com mais sabedoria.', 'Provérbios 19:20'),
(84, 'Mesmo atravessando fases intensas, você não será vencido, porque Deus está com você.', 'Isaías 43:2'),
(85, 'Não se deixe vencer pelo mal; vença o mal com o bem.', 'Romanos 12:21'),
(86, 'A verdadeira sabedoria aparece numa vida marcada por mansidão e boas obras.', 'Tiago 3:13'),
(87, 'Se o próprio Cristo serviu com humildade, vocês também devem servir uns aos outros.', 'João 13:14-15'),
(88, 'É Deus quem dá descanso aos seus amados.', 'Salmos 127:2'),
(89, 'As mãos diligentes conduzem à boa administração e ao resultado consistente.', 'Provérbios 10:4'),
(90, 'Pensem em como incentivar uns aos outros ao amor e às boas obras.', 'Hebreus 10:24'),
(91, 'Ame o Senhor de todo o coração, de toda a alma e com toda a força.', 'Deuteronômio 6:5'),
(92, 'Age com bondade quem conduz seus assuntos com justiça.', 'Salmos 112:5'),
(93, 'Quem caminha com pessoas sábias cresce em sabedoria.', 'Provérbios 13:20'),
(94, 'Podemos ser pressionados, mas não destruídos; abatidos, mas não derrotados.', '2 Coríntios 4:8-9'),
(95, 'Confiem no Senhor para sempre, pois nele há firmeza duradoura.', 'Isaías 26:4'),
(96, 'Tudo o que fizerem, em palavras ou ações, façam com propósito e gratidão diante de Deus.', 'Colossenses 3:17'),
(97, 'Quando você cuida de alguém em necessidade, esse cuidado tem valor diante de Deus.', 'Mateus 25:40'),
(98, 'Cada pessoa foi criada de modo admirável e precioso.', 'Salmos 139:14'),
(99, 'Se você enfraquece no dia da dificuldade, sua força ainda precisa ser fortalecida.', 'Provérbios 24:10'),
(100, 'Até aqui o Senhor nos ajudou.', '1 Samuel 7:12'),
(101, 'Com boa direção e conselhos sábios, a liderança se torna mais segura e estável.', 'Provérbios 11:14'),
(102, 'Deus cura os corações feridos e trata as feridas com cuidado.', 'Salmos 147:3'),
(103, 'Sejam misericordiosos, assim como o Pai de vocês é misericordioso.', 'Lucas 6:36'),
(104, 'Não se entregue facilmente à irritação; a calma protege o coração e a decisão.', 'Eclesiastes 7:9'),
(105, 'Aproxime-se de Deus com confiança para receber graça e socorro no momento certo.', 'Hebreus 4:16'),
(106, 'Deus dá palavra sábia ao cansado para sustentar quem precisa de alívio.', 'Isaías 50:4'),
(107, 'Ame o seu próximo como a si mesmo.', 'Marcos 12:31'),
(108, 'A sabedoria é o principal; busque-a com dedicação.', 'Provérbios 4:7'),
(109, 'Bendiga ao Senhor e não se esqueça dos benefícios dele, que restaura e sustenta a vida.', 'Salmos 103:2-4'),
(110, 'Cuidem uns dos outros com igual atenção e responsabilidade.', '1 Coríntios 12:25'),
(111, 'Feliz quem persevera na provação, porque permanece firme depois da pressão.', 'Tiago 1:12'),
(112, 'A mente sensata busca conhecimento e continua aprendendo.', 'Provérbios 18:15'),
(113, 'Jesus viu a multidão, teve compaixão e cuidou dos que estavam enfermos.', 'Mateus 14:14'),
(114, 'É Deus quem estabelece paz e firma o que realizamos.', 'Isaías 26:12'),
(115, 'No que depender de vocês, vivam em paz com todos.', 'Romanos 12:18'),
(116, 'Os planos de quem trabalha com diligência produzem bons frutos.', 'Provérbios 21:5'),
(117, 'O Senhor cumprirá o propósito dele em sua vida.', 'Salmos 138:8'),
(118, 'Toda a lei se resume em amar o próximo como a si mesmo.', 'Gálatas 5:14'),
(119, 'Olhe para Cristo e não se entregue ao cansaço da alma.', 'Hebreus 12:3'),
(120, 'A ansiedade pesa o coração, mas uma palavra certa traz alívio.', 'Provérbios 12:25'),
(121, 'Felizes os que promovem a paz.', 'Mateus 5:9'),
(122, 'Seja como abrigo para quem está exposto à dor e ao desgaste.', 'Isaías 32:2'),
(123, 'Dedique-se ao trabalho com integridade, como alguém aprovado diante de Deus.', '2 Timóteo 2:15'),
(124, 'Senhor, mostra-me o caminho certo e guia-me na tua verdade.', 'Salmos 25:4-5'),
(125, 'Palavras amáveis trazem doçura à alma e renovam até o corpo.', 'Provérbios 16:24'),
(126, 'Vá em paz; Deus vê a sua dor e traz restauração.', 'Lucas 8:48'),
(127, 'Que Deus lhes dê perseverança e encorajamento para caminharem em unidade.', 'Romanos 15:5'),
(128, 'Não deixe de fazer o bem a quem precisa, quando estiver ao seu alcance agir.', 'Provérbios 3:27'),
(129, 'O choro pode durar uma noite, mas a alegria chega com a manhã.', 'Salmos 30:5'),
(130, 'O amor visível no cuidado é a marca de quem pertence a Cristo.', 'João 13:35'),
(131, 'A justiça floresce onde há paz semeada por quem promove reconciliação.', 'Tiago 3:18'),
(132, 'Quem planeja o bem encontra bondade e fidelidade no caminho.', 'Provérbios 14:22'),
(133, 'O Senhor guia continuamente, satisfaz e fortalece mesmo em tempos de desgaste.', 'Isaías 58:11'),
(134, 'Deus nos consola para que também possamos consolar os que sofrem.', '2 Coríntios 1:3-4'),
(135, 'Em Deus há socorro; nele a alma encontra sustento e firmeza.', 'Salmos 63:7-8'),
(136, 'A compaixão verdadeira se transforma em cuidado prático e presença real.', 'Lucas 10:34'),
(137, 'A sabedoria ajuda a discernir o caminho certo com clareza.', 'Provérbios 14:8'),
(138, 'Permaneça em Cristo, porque sem ele não há fruto duradouro.', 'João 15:5'),
(139, 'Não abandone a confiança; é pela perseverança que se alcança a promessa.', 'Hebreus 10:35-36'),
(140, 'Ensina-me bom senso e conhecimento para que eu decida com retidão.', 'Salmos 119:66'),
(141, 'Quem controla as palavras demonstra entendimento e maturidade.', 'Provérbios 17:27'),
(142, 'Viva um dia de cada vez; cada dia já tem seus próprios desafios.', 'Mateus 6:34'),
(143, 'Fortaleçam as mãos cansadas e firmem os joelhos vacilantes.', 'Isaías 35:3-4'),
(144, 'Sirvam com zelo, constância e dedicação.', 'Romanos 12:11'),
(145, 'A fidelidade produz frutos e bênçãos ao longo do caminho.', 'Provérbios 28:20'),
(146, 'Entregue seu fardo ao Senhor, e ele o sustentará.', 'Salmos 55:22'),
(147, 'Fortaleçam-se no Senhor e na força do poder dele.', 'Efésios 6:10'),
(148, 'Vivam de modo digno, frutificando em toda boa obra e crescendo em conhecimento.', 'Colossenses 1:10'),
(149, 'Amparam os fracos, encorajem os desanimados e sejam pacientes com todos.', '1 Tessalonicenses 5:14'),
(150, 'Com sabedoria se constrói, e com entendimento se firma o que foi confiado às suas mãos.', 'Provérbios 24:3'),
(151, 'Quem fala com sabedoria e ensina com bondade transmite cuidado e segurança.', 'Provérbios 31:26'),
(152, 'Mostra-me pela manhã o teu amor, pois em ti eu confio; guia-me no caminho que devo seguir.', 'Salmos 143:8'),
(153, 'Tudo o que vocês querem que as pessoas lhes façam, façam também a elas.', 'Mateus 7:12'),
(154, 'A ira humana não produz a justiça que Deus deseja.', 'Tiago 1:20'),
(155, 'O Senhor cuida do seu povo com ternura, como pastor que carrega os mais frágeis.', 'Isaías 40:11'),
(156, 'Quem lidera, faça isso com dedicação e zelo.', 'Romanos 12:8'),
(157, 'Semeie com constância; você não sabe qual esforço dará melhor fruto.', 'Eclesiastes 11:6'),
(158, 'Permaneça o amor fraternal e não deixem de praticar a hospitalidade.', 'Hebreus 13:1-2'),
(159, 'Jesus chorou.', 'João 11:35'),
(160, 'Deus faz justiça ao vulnerável e ama quem precisa de cuidado e acolhimento.', 'Deuteronômio 10:18'),
(161, 'A língua dos sábios promove saúde e restauração.', 'Provérbios 12:18'),
(162, 'Espera no Senhor, seja forte e não desanime.', 'Salmos 27:14'),
(163, 'Ao ver a dor de uma família, Jesus se aproximou com compaixão e trouxe esperança.', 'Lucas 7:13'),
(164, 'Façam tudo para a glória de Deus.', '1 Coríntios 10:31'),
(165, 'O coração do sábio torna suas palavras prudentes e úteis.', 'Provérbios 16:23'),
(166, 'Busquem o bem-estar uns dos outros e o que promove paz.', '1 Tessalonicenses 5:15'),
(167, 'Deus fortalece a mão cansada e renova quem está abatido.', 'Isaías 35:3'),
(168, 'O Senhor ampara quem está curvado pelo peso e pelo cansaço.', 'Salmos 146:8'),
(169, 'Quem tem compaixão do necessitado honra a Deus.', 'Provérbios 14:31'),
(170, 'Jesus passou fazendo o bem e trazendo restauração aos oprimidos.', 'Atos 10:38'),
(171, 'Tenham sempre prontidão para servir, com mansidão e respeito.', '1 Pedro 3:15'),
(172, 'É melhor ser paciente do que poderoso; dominar a si mesmo vale mais que conquistar grandes coisas.', 'Provérbios 16:32'),
(173, 'O Senhor abre os olhos dos que não conseguem ver com clareza e sustenta os abatidos.', 'Salmos 146:7-8'),
(174, 'Sejam compassivos e humildes uns para com os outros.', '1 Pedro 3:8'),
(175, 'Um bom nome vale mais que grandes riquezas.', 'Provérbios 22:1'),
(176, 'Deus fortalece vocês em toda boa obra e palavra.', '2 Tessalonicenses 2:16-17'),
(177, 'Os passos da pessoa íntegra são dirigidos pelo Senhor.', 'Provérbios 20:24'),
(178, 'Tu me dás força e tornas firme o meu caminho.', 'Salmos 18:32-33'),
(179, 'Jesus acolheu as crianças, tocou nelas e as abençoou.', 'Marcos 10:16'),
(180, 'A sabedoria preserva a vida de quem a possui.', 'Eclesiastes 7:12'),
(181, 'Falem de modo que encoraje e faça bem a quem ouve.', 'Efésios 4:29'),
(182, 'Volte ao seu descanso, minha alma, pois o Senhor tem sido bom para você.', 'Salmos 116:7'),
(183, 'Quem anda com retidão teme ao Senhor; quem age de forma torta despreza esse caminho.', 'Provérbios 14:2'),
(184, 'Levemos uma vida tranquila, digna e serena em tudo.', '1 Timóteo 2:2'),
(185, 'O Senhor é bom para todos; sua compaixão alcança tudo o que ele fez.', 'Salmos 145:9'),
(186, 'Resgatem quem está sendo levado ao sofrimento e não deixem de socorrer quem corre risco.', 'Provérbios 24:11'),
(187, 'Jesus tomou nossas dores sobre si e carregou nossos sofrimentos.', 'Mateus 8:17'),
(188, 'Sejam firmes, maduros e inabaláveis na fé.', '1 Pedro 5:9'),
(189, 'O caminho da justiça conduz à vida.', 'Provérbios 12:28'),
(190, 'O Senhor satisfaz a alma exausta e renova quem desfalece.', 'Jeremias 31:25'),
(191, 'Quando um membro sofre, todos sofrem com ele; quando um é honrado, todos se alegram juntos.', '1 Coríntios 12:26'),
(192, 'O justo cuida até dos detalhes da vida que lhe foi confiada.', 'Provérbios 12:10'),
(193, 'O Senhor é misericordioso e compassivo, paciente e cheio de amor.', 'Salmos 103:8'),
(194, 'Suportem-se com paciência em amor e preservem a unidade.', 'Efésios 4:2-3'),
(195, 'A esperança adiada entristece o coração, mas a resposta que chega no tempo certo renova a vida.', 'Provérbios 13:12'),
(196, 'Jesus chamava as pessoas pelo nome e restaurava sua dignidade.', 'João 20:16'),
(197, 'Tu conservas em perfeita paz aquele cujo propósito está firme em ti.', 'Isaías 26:3'),
(198, 'Revistam-se do amor, que une tudo com perfeição.', 'Colossenses 3:14'),
(199, 'Os planos do diligente conduzem à abundância; a pressa leva à falta.', 'Provérbios 21:5'),
(200, 'Esquecendo o que ficou para trás e avançando para o que está adiante, prossigo para o alvo com perseverança.', 'Filipenses 3:13-14'),
(201, 'Aquele que convive com pessoas sábias cresce em sabedoria e amadurece no caminho.', 'Provérbios 13:20'),
(202, 'O Senhor é minha força e meu escudo; nele meu coração confia e encontra socorro.', 'Salmos 28:7'),
(203, 'Jesus disse que não são os saudáveis que precisam de médico, mas os doentes.', 'Lucas 5:31'),
(204, 'A sabedoria torna o rosto sereno e suaviza até as expressões mais duras.', 'Eclesiastes 8:1'),
(205, 'Permaneçam dedicados à oração, vigilantes e cheios de gratidão.', 'Colossenses 4:2'),
(206, 'Quem serve bem lidera bem quando faz isso com integridade e diligência.', 'Romanos 12:8'),
(207, 'Palavras corretas no momento certo são preciosas e trazem direção.', 'Provérbios 25:11'),
(208, 'Entrega seu caminho ao Senhor; ele fortalece e endireita os seus passos.', 'Salmos 37:5-6'),
(209, 'A compaixão se expressa em atitude, não apenas em intenção.', '1 João 3:18'),
(210, 'Deus não é injusto para se esquecer do seu trabalho e do amor demonstrado no serviço.', 'Hebreus 6:10'),
(211, 'O prudente adquire conhecimento, e o sábio continua atento para aprender mais.', 'Provérbios 18:15'),
(212, 'Aquietem o coração e reconheçam que Deus continua no controle.', 'Salmos 46:10'),
(213, 'Jesus se retirava para lugares silenciosos para orar e renovar as forças.', 'Lucas 5:16'),
(214, 'Há mais proveito quando o trabalho é feito com atenção, ordem e constância.', 'Eclesiastes 10:10'),
(215, 'Façam tudo com amor.', '1 Coríntios 16:14'),
(216, 'Escolha pessoas capazes, confiáveis e íntegras para dividir responsabilidades.', 'Êxodo 18:21'),
(217, 'O coração sábio discerne o tempo e a maneira certa de agir.', 'Eclesiastes 8:5'),
(218, 'O Senhor firma os passos de quem encontra prazer em andar corretamente.', 'Salmos 37:23'),
(219, 'Alegrem-se na esperança, suportem com paciência a tribulação e perseverem na oração.', 'Romanos 12:12'),
(220, 'O sábio observa bem o estado daquilo que está sob seus cuidados.', 'Provérbios 27:23'),
(221, 'Quando você passar por águas profundas, Deus estará com você.', 'Isaías 43:2'),
(222, 'Se alguém estiver sem forças, seja restaurado com espírito de mansidão e cuidado.', 'Gálatas 6:1'),
(223, 'Melhor é ter entendimento do que apenas força; discernimento vale muito.', 'Provérbios 24:5'),
(224, 'Deus satisfaz a vida sedenta e renova quem está esgotado.', 'Salmos 107:9'),
(225, 'Carreguem os pesos uns dos outros e vivam o cuidado mútuo.', 'Gálatas 6:2'),
(226, 'O temor do Senhor é fonte de vida e afasta dos caminhos de destruição.', 'Provérbios 14:27'),
(227, 'O Senhor abre caminho no deserto e faz brotar recursos onde parecia impossível.', 'Isaías 43:19'),
(228, 'O amor ao próximo cumpre aquilo que é essencial diante de Deus.', 'Romanos 13:10'),
(229, 'Quem domina a si mesmo demonstra mais força do que quem vence grandes batalhas.', 'Provérbios 16:32'),
(230, 'Deus cura os de coração quebrantado e trata suas feridas com cuidado.', 'Salmos 147:3'),
(231, 'Jesus tocou o doente com compaixão e trouxe restauração.', 'Marcos 1:41'),
(232, 'A palavra sábia é como árvore de vida para quem a recebe.', 'Provérbios 15:4'),
(233, 'O Senhor revigora a alma e conduz por caminhos corretos.', 'Salmos 23:3'),
(234, 'Quem deseja amar a vida deve guardar a língua do mal e escolher o bem.', '1 Pedro 3:10-11'),
(235, 'Os pensamentos de quem busca justiça produzem direção reta.', 'Provérbios 12:5'),
(236, 'O Senhor fortalece o desanimado e multiplica as forças do exausto.', 'Isaías 40:29'),
(237, 'Sirvam uns aos outros com o dom que receberam, como bons administradores da graça.', '1 Pedro 4:10'),
(238, 'Com sabedoria uma casa é construída, e com entendimento ela permanece firme.', 'Provérbios 24:3'),
(239, 'A bondade e a fidelidade não devem se afastar de você; leve-as sempre consigo.', 'Provérbios 3:3'),
(240, 'O Deus da esperança enche vocês de alegria e paz enquanto confiam nele.', 'Romanos 15:13'),
(241, 'Quem anda em integridade caminha em segurança.', 'Provérbios 10:9'),
(242, 'O Senhor é quem dá força ao seu povo e o abençoa com paz.', 'Salmos 29:11'),
(243, 'Sejam humildes, gentis e pacientes no trato uns com os outros.', 'Efésios 4:2'),
(244, 'Há caminho que parece certo aos olhos humanos, por isso é preciso discernimento.', 'Provérbios 14:12'),
(245, 'A alegria que vem de Deus fortalece o coração para continuar.', 'Neemias 8:10'),
(246, 'Suportem-se com amor e procurem preservar a unidade.', 'Colossenses 3:13-14'),
(247, 'Os planos do diligente conduzem à boa provisão; a pressa leva à perda.', 'Provérbios 21:5'),
(248, 'Ensina-nos a fazer a tua vontade, pois tu és o nosso Deus.', 'Salmos 143:10'),
(249, 'O amor é paciente, bondoso e não busca seus próprios interesses.', '1 Coríntios 13:4-5'),
(250, 'Confie no Senhor e faça o bem; permaneça fiel e siga cultivando o que é correto.', 'Salmos 37:3'),
(251, 'Quem aceita correção e escuta orientação amadurece em sabedoria.', 'Provérbios 15:31'),
(252, 'O Senhor não dorme; ele vela por você e sustenta seus passos.', 'Salmos 121:3-4'),
(253, 'Jesus se aproximava das pessoas feridas com compaixão e as restaurava.', 'Mateus 14:14'),
(254, 'Melhor é ter paciência do que agir com orgulho e impulsividade.', 'Eclesiastes 7:8'),
(255, 'Permaneçam firmes no amor e sirvam uns aos outros com disposição.', '1 Coríntios 16:13-14'),
(256, 'O coração sábio busca conhecimento antes de agir.', 'Provérbios 15:14'),
(257, 'Deus fortalece quem está cansado e renova quem já não tem vigor.', 'Isaías 40:31'),
(258, 'Sejam humildes e considerem o outro com atenção genuína.', 'Filipenses 2:3'),
(259, 'O Senhor é bondoso e compassivo em tudo o que faz.', 'Salmos 145:17'),
(260, 'Quem cuida bem do que lhe foi confiado demonstra fidelidade verdadeira.', 'Lucas 12:42-43'),
(261, 'O plano dá certo quando é guiado por discernimento e prudência.', 'Provérbios 14:15'),
(262, 'Deus vai adiante de você, abrindo caminho e trazendo segurança.', 'Deuteronômio 31:8'),
(263, 'Sejam pacientes com todos e façam o bem sem desistir.', '1 Tessalonicenses 5:14-15'),
(264, 'A sabedoria traz serenidade até para os dias mais exigentes.', 'Eclesiastes 8:1'),
(265, 'O Senhor sustenta quem está exausto e levanta quem já não consegue mais sozinho.', 'Salmos 145:14'),
(266, 'O amor deve ser sincero; rejeitem o mal e apeguem-se ao bem.', 'Romanos 12:9'),
(267, 'A resposta prudente preserva relacionamentos e reduz tensões.', 'Provérbios 15:4'),
(268, 'Deus promete estar com você em cada travessia difícil.', 'Isaías 43:2'),
(269, 'Cristo deixou exemplo para que vocês sigam seus passos com fidelidade.', '1 Pedro 2:21'),
(270, 'Tudo tem seu tempo certo, inclusive os processos que exigem paciência.', 'Eclesiastes 3:11'),
(271, 'Guie quem está sob seus cuidados com justiça, verdade e equilíbrio.', 'Provérbios 29:14'),
(272, 'O Senhor é quem dá sabedoria; dele vêm conhecimento e entendimento.', 'Provérbios 2:6'),
(273, 'Descanse em Deus e espere nele com confiança.', 'Salmos 37:7'),
(274, 'A compaixão de Cristo se revela em cuidado real com quem sofre.', 'Mateus 20:34'),
(275, 'Suportem uns aos outros com amor e preservem a unidade.', 'Efésios 4:2-3'),
(276, 'A pessoa prudente pensa antes de responder e escolhe bem as palavras.', 'Provérbios 15:28'),
(277, 'Deus é abrigo seguro e socorro presente em qualquer pressão.', 'Salmos 46:1'),
(278, 'Alegrem-se sempre, orem continuamente e deem graças em todas as circunstâncias.', '1 Tessalonicenses 5:16-18'),
(279, 'Quem administra com diligência evita perdas e conduz melhor o que lhe foi confiado.', 'Provérbios 27:18'),
(280, 'O Senhor o conduzirá continuamente e renovará suas forças.', 'Isaías 58:11'),
(281, 'Jesus parou, ouviu a necessidade de quem sofria e respondeu com cuidado.', 'Marcos 10:51-52'),
(282, 'Seja firme no coração e não deixe o medo governar suas decisões.', 'Salmos 27:14'),
(283, 'Os pensamentos do justo são guiados por retidão e responsabilidade.', 'Provérbios 12:5'),
(284, 'Revistam-se de compaixão, bondade e mansidão no trato com as pessoas.', 'Colossenses 3:12'),
(285, 'A sabedoria fortalece mais do que a força física.', 'Eclesiastes 7:19'),
(286, 'Deus é quem aperfeiçoa, firma, fortalece e fundamenta vocês.', '1 Pedro 5:10'),
(287, 'Quem é generoso ao cuidar dos outros também será renovado.', 'Provérbios 11:25'),
(288, 'O Senhor torna leve o caminho de quem entrega a ele seu coração.', 'Salmos 55:22'),
(289, 'Façam o bem a todos, especialmente aos que estão perto de vocês.', 'Gálatas 6:10'),
(290, 'A palavra certa, dita no momento certo, traz direção e alívio.', 'Provérbios 25:11'),
(291, 'Deus é quem prepara as mãos para a batalha e dá força para continuar.', 'Salmos 18:34'),
(292, 'Cuidem dos enfermos e levem esperança, porque o Reino de Deus se aproxima com misericórdia.', 'Mateus 10:8'),
(293, 'A sabedoria protege quem a abraça e honra quem a valoriza.', 'Provérbios 4:8-9'),
(294, 'O Senhor restaura a alma e conduz por caminhos corretos.', 'Salmos 23:3'),
(295, 'Sirvam com os dons que receberam, como bons administradores da graça de Deus.', '1 Pedro 4:10'),
(296, 'É melhor agir com calma e entendimento do que com pressa e confusão.', 'Provérbios 19:2'),
(297, 'Mesmo no vale mais escuro, Deus permanece presente e fiel.', 'Salmos 23:4'),
(298, 'Jesus acolheu os cansados e ofereceu descanso verdadeiro.', 'Mateus 11:28-29'),
(299, 'A integridade preserva quem caminha com retidão.', 'Provérbios 10:9'),
(300, 'Que Deus os fortaleça com poder interior para seguirem firmes no propósito.', 'Efésios 3:16'),
(301, 'Quem aceita correção anda no caminho da vida e amadurece em sabedoria.', 'Provérbios 10:17'),
(302, 'A palavra de Deus ilumina o caminho e ajuda a dar o próximo passo com clareza.', 'Salmos 119:105'),
(303, 'As pessoas buscavam aproximação porque de Jesus saía poder que trazia restauração.', 'Lucas 6:19'),
(304, 'A oração feita com fé sustenta, levanta e participa do processo de cura.', 'Tiago 5:15'),
(305, 'Deus habita com os humildes para restaurar o ânimo e reanimar o coração abatido.', 'Isaías 57:15'),
(306, 'Vivam em harmonia, sem arrogância, tratando todos com humildade e respeito.', 'Romanos 12:16'),
(307, 'A bondade e a fidelidade sustentam a liderança e a tornam estável.', 'Provérbios 20:28'),
(308, 'Nossa esperança está no Senhor; nele encontramos ajuda e proteção.', 'Salmos 33:20-22'),
(309, 'Se é certo fazer o bem, então o cuidado nunca deve ser adiado.', 'Mateus 12:12'),
(310, 'Quando caminham juntos, vocês se tornam mais fortes e mais resistentes.', 'Eclesiastes 4:12'),
(311, 'Encorajem uns aos outros todos os dias para que ninguém endureça o coração.', 'Hebreus 3:13'),
(312, 'Quem ama aprender acolhe a disciplina; rejeitar correção é recusar crescimento.', 'Provérbios 12:1'),
(313, 'Afaste-se do mal, pratique o bem, busque a paz e empenhe-se por ela.', 'Salmos 34:14'),
(314, 'Que Deus fortaleça vocês com toda força para perseverarem com paciência e alegria.', 'Colossenses 1:11'),
(315, 'Não julguem apenas pela aparência; decidam com justiça e discernimento.', 'João 7:24'),
(316, 'Aprendam a fazer o bem, pratiquem a justiça e defendam quem precisa de cuidado.', 'Isaías 1:17'),
(317, 'Mesmo que por fora haja desgaste, por dentro Deus renova dia após dia.', '2 Coríntios 4:16'),
(318, 'A reverência a Deus forma o coração sábio, e a humildade vem antes da honra.', 'Provérbios 15:33'),
(319, 'Quem confia no Senhor não vive dominado pelo medo das más notícias.', 'Salmos 112:7'),
(320, 'Não tenha medo; apenas continue confiando.', 'Lucas 8:50'),
(321, 'Dirijam a mente ao que é verdadeiro, justo, puro e digno de louvor.', 'Filipenses 4:8'),
(322, 'A pessoa sensata mantém os olhos na direção certa e não perde o foco do caminho.', 'Provérbios 17:24'),
(323, 'Quem está firmado em Deus continua frutificando mesmo com o passar do tempo.', 'Salmos 92:12-14'),
(324, 'Vocês são luz; deixem que essa luz alcance quem está ao redor.', 'Mateus 5:14'),
(325, 'A misericórdia triunfa sobre o julgamento rígido.', 'Tiago 2:13'),
(326, 'As palavras têm poder para trazer vida ou aprofundar feridas; use-as com sabedoria.', 'Provérbios 18:21'),
(327, 'Sabedoria e conhecimento trazem estabilidade para os dias difíceis.', 'Isaías 33:6'),
(328, 'Mantenham firme a esperança, porque Deus é fiel ao que prometeu.', 'Hebreus 10:23'),
(329, 'Busquem aquilo que promove paz e edifica as pessoas.', 'Romanos 14:19'),
(330, 'Todo trabalho dedicado produz fruto; a fala vazia não sustenta resultados.', 'Provérbios 14:23'),
(331, 'Deus é refúgio seguro e proteção em meio ao desgaste.', 'Salmos 119:114'),
(332, 'O maior amor se revela quando alguém entrega a vida pelos outros.', 'João 15:13'),
(333, 'Continue semeando o bem; no tempo certo, o fruto aparecerá.', 'Eclesiastes 11:1'),
(334, 'Quem serve a Deus não deve ser agressivo, mas amável, paciente e apto para orientar.', '2 Timóteo 2:24-25'),
(335, 'Feliz quem encontra sabedoria, porque ela vale mais do que qualquer ganho material.', 'Provérbios 3:13-14'),
(336, 'Esperei no Senhor, e ele me ouviu, me levantou e firmou meus passos.', 'Salmos 40:1-2'),
(337, 'A quem muito foi confiado, também muito será requerido.', 'Lucas 12:48'),
(338, 'Examine o próprio trabalho com responsabilidade e fidelidade.', 'Gálatas 6:4-5'),
(339, 'No coração humano há questões profundas; a pessoa sensata sabe trazê-las à luz.', 'Provérbios 20:5'),
(340, 'Deus envia cuidado, consolo e boas notícias para os corações quebrantados.', 'Isaías 61:1'),
(341, 'Que o amor de vocês cresça e transborde uns para com os outros.', '1 Tessalonicenses 3:12'),
(342, 'Felizes os que encontram força em Deus e seguem avançando de etapa em etapa.', 'Salmos 84:5-7'),
(343, 'O caminho de quem anda corretamente se torna cada vez mais claro.', 'Provérbios 4:18'),
(344, 'Jesus chamou os cansados para um tempo de pausa e renovação.', 'Marcos 6:31'),
(345, 'A esperança em Deus é âncora firme para a alma.', 'Hebreus 6:19'),
(346, 'Assim como o ferro afia o ferro, pessoas comprometidas fortalecem umas às outras.', 'Provérbios 27:17'),
(347, 'Descanse somente em Deus, porque dele vem a sua esperança e firmeza.', 'Salmos 62:5-6'),
(348, 'Vocês foram criados para realizar boas obras com propósito.', 'Efésios 2:10'),
(349, 'Não deixem o coração ficar perturbado; confiem em Deus.', 'João 14:1'),
(350, 'Pense bem no caminho por onde anda e mantenha seus passos firmes.', 'Provérbios 4:26'),
(351, 'O coração sábio é reconhecido pelo discernimento, e suas palavras trazem direção e aprendizado.', 'Provérbios 16:21'),
(352, 'O melhor para mim é estar perto de Deus e fazer dele o meu refúgio.', 'Salmos 73:28'),
(353, 'Quando vocês cuidam de quem está enfermo, esse cuidado tem grande valor diante de Deus.', 'Mateus 25:36'),
(354, 'Tudo o que suas mãos encontrarem para fazer, façam com toda a dedicação.', 'Eclesiastes 9:10'),
(355, 'Que tudo seja feito com ordem, respeito e bom senso.', '1 Coríntios 14:40'),
(356, 'Não tenha medo, porque Deus segura sua mão e o ajuda.', 'Isaías 41:13'),
(357, 'Os mais fortes devem sustentar os mais frágeis e buscar o bem do próximo.', 'Romanos 15:1-2'),
(358, 'Quem lidera bem observa com atenção aquilo que está sob sua responsabilidade.', 'Provérbios 31:27'),
(359, 'Hoje nasceu o Salvador, Cristo, o Senhor.', 'Lucas 2:11'),
(360, 'Cristo conhece as nossas fraquezas e se compadece de nós.', 'Hebreus 4:15'),
(361, 'Sejam sábios na forma de agir com as pessoas, falando com graça e discernimento.', 'Colossenses 4:5-6'),
(362, 'Um olhar sereno e uma boa notícia renovam o coração e fortalecem até o corpo.', 'Provérbios 15:30'),
(363, 'O Senhor é quem guarda você e permanece ao seu lado.', 'Salmos 121:5'),
(364, 'Quem reconhece a graça recebida volta com gratidão.', 'Lucas 17:15-16'),
(365, 'Que o amor de vocês cresça em conhecimento e discernimento para escolher o que é melhor.', 'Filipenses 1:9-10'),
(366, 'Este dia também está nas mãos de Deus; viva-o com alegria e gratidão.', 'Salmos 118:24');

-- Add unique constraint
ALTER TABLE daily_verses ADD CONSTRAINT daily_verses_day_of_year_unique UNIQUE (day_of_year);

-- Create function to get daily verse with leap year handling
CREATE OR REPLACE FUNCTION get_daily_verse(target_date DATE DEFAULT CURRENT_DATE)
RETURNS TABLE (
  day_of_year INT,
  verse_text TEXT,
  verse_reference TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH date_info AS (
    SELECT
      target_date AS dt,
      EXTRACT(YEAR FROM target_date)::INT AS yr,
      EXTRACT(MONTH FROM target_date)::INT AS mon,
      EXTRACT(DAY FROM target_date)::INT AS dy,
      EXTRACT(DOY FROM target_date)::INT AS doy
  ),
  mapped_day AS (
    SELECT
      CASE
        WHEN mon = 2 AND dy = 29 THEN 366
        WHEN ((yr % 400 = 0) OR (yr % 4 = 0 AND yr % 100 <> 0)) AND doy > 60 THEN doy - 1
        ELSE doy
      END AS final_day
    FROM date_info
  )
  SELECT dv.day_of_year, dv.verse_text, dv.verse_reference
  FROM daily_verses dv
  JOIN mapped_day md
    ON dv.day_of_year = md.final_day;
$$;
